### ISSUE TITLE
wsl2-ssh-pageant.exe missing?

### ISSUE THREAD

**Issue by JeGr** [BlackReloaded/wsl2-ssh-pageant#13]
Seems the socat target file is no longer attached to this project?

**Comment by tobiaskohlbau** [comment]
Did you resolve this for yourself? I don't get your point. If you could writeup your solution this maybe helps someone else in the future.

**Comment by JeGr** [comment]
Sorry, it was an honest mistake as the "Releases" moved from the top to the right and I didn't find them in my tired state ;) Realized later that the "Tab" I searched for is actually a box on the right now :)

Perhaps would be nice to link the EXE pr release page (https://github.com/BlackReloaded/wsl2-ssh-pageant/releases) in the README.md so it's clear in the documentation part as to where to download it.
