### ISSUE TITLE
agent refused operation when running ssh-add -L

### ISSUE THREAD

**Issue by r1cebank** [BlackReloaded/wsl2-ssh-pageant#15]
**Describe the bug**
After installation, when trying to run `ssh-add -L` in WSL, it returns error:

```
➜ ssh-add -L
error fetching identities: agent refused operation
```

**To Reproduce**
1. Follow installation step
2. Run `ssh-add -L`

**Expected behavior**
List of key from my yubikey

**Desktop (please complete the following information):**
 - OS: Windows 10 2004

**Additional context**
Using gpg4win, yubikey, zsh

When running `gpg --card-status` in WSL, the command works fine.

Any help on debugging this is appreciated. 👍

**Comment by BlackReloaded** [comment]
Hi,

have you tried:
 - is socat still running: `ss -a | grep $SSH_AUTH_SOCK`
 - Sometimes yubikey blocks, try to remove it from usb port and try again.

**Comment by r1cebank** [comment]
Hi, thanks for your reply, running `ss -a | grep $SSH_AUTH_SOCK` gives me this:
```
➜ ss -a | grep $SSH_AUTH_SOCK
u_str              LISTEN              0                    5
           /home/rbnk/.ssh/agent.sock 2551                                     * 0
```
I have tried removing from the port and still no luck, I also tried shutting down WSL and restarting.

**Comment by BlackReloaded** [comment]
Is this a new yubikey or has it worked already?

If it is new check this site to enable ssh support: https://developers.yubico.com/PGP/SSH_authentication/Windows.html
If it is old, is putty working on windows?

**Comment by r1cebank** [comment]
Its a old key I've been using with my arch machine, looks like the tip in your above link worked! Thanks 👍 

```
gpg-connect-agent killagent /bye
gpg-connect-agent /bye
```

**Comment by tobiaskohlbau** [comment]
@r1cebank maybe it's worth stating some FAQ/Debug options in the README. Are you willing to contribute such section?

**Comment by r1cebank** [comment]
@tobiaskohlbau Sure, I will submit a PR soon

**Comment by hr3lxphr6j** [comment]
Hello, I encountered the same problem, but can not be solved by restarting agent.
`gpg --card-status` is WSL2 can work, and putty can work.
```
$ ss -a | grep $SSH_AUTH_SOCK
u_str  LISTEN  0        5             /home/chigusa/.ssh/agent.sock 23555                                   *

$ ssh-add -L
error fetching identities: agent refused operation

$ tail -f nohup.out
2021/08/02 21:38:01 Reading length: 1
2021/08/02 21:38:01 Querying pageant
```

**Comment by tobiaskohlbau** [comment]
Maybe related to #23? Do you use putty version 0.75?

Just to clarify that I got your point. GPG is working and SSH inside wsl is not working?

**Comment by hr3lxphr6j** [comment]
> Maybe related to #23? Do you use putty version 0.75?
> 
> Just to clarify that I got your point. GPG is working and SSH inside wsl is not working?
The version of putty is 0.76, and it works fine.

Yes, gpg in wsl works fine, but ssh-add returns an error

**Comment by tobiaskohlbau** [comment]
Did you try to use the workaround from #23? Putty itself is working fine but the communicatin between wsl2-ssh-pageant and putty looks like it's broken in newer versions.
