### ISSUE TITLE
RTNETLINK answers: Invalid argument

### ISSUE THREAD

**Issue by plttn** [BlackReloaded/wsl2-ssh-pageant#17]
```
socat version 1.7.3.4 on Apr 25 2020 06:17:10
   running on Linux version #1 SMP Wed Feb 19 06:37:35 UTC 2020, release 4.19.104-microsoft-standard, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
```

After updating my Pengwin install, I get two `RTNETLINK` messages on console start. Everything appears to function fine, just it complaining about a bad argument.

**Comment by tobiaskohlbau** [comment]
This is not an issue within _wsl2-ssh-pageant_ nor within socat. The output `RTNETLINK answers: Invalid argument` is a result of `ss -a` which checks for already running instance of the socat proxy. Looks like the tool was upgraded which is not compatible with WSL.

A quick look resulted in ubuntu 20.04 (working for me) using version [_v5.5.0_](https://packages.ubuntu.com/focal/iproute2) and pengwin using (_v5.10.0_)[https://packages.debian.org/bullseye/iproute2). Bisecting the two version on pengwin resulted in [this commit](https://github.com/shemminger/iproute2/commit/9c3be2c0eee01be7832b7900a8be798a19c659a5) being the issue. It's either an issue with WSL or the iproute2 package. I would assume the current WSL kernel does not have a feature enabled which iproute2 assumes. Therefore it's most likely an issue to raise on the [WSL repository](https://github.com/Microsoft/wsl).

**Comment by plttn** [comment]
Thanks for pointing me in the right direction. Since it still works, it's not the end of the world for now.

**Comment by tm-drtina** [comment]
I've hit the same issue while upgrading my WSL distro from debian 10 to 11.
Current versions of iproute2 in apt:
```
$ sudo apt list -a iproute2
Listing... Done
iproute2/bullseye-backports 5.14.0-1~bpo11+1 amd64
iproute2/stable,now 5.10.0-4 amd64 [installed]
```

It seems that the `5.14.0` version works correctly, so you can fix this issue in Debian 11 by running:
`sudo apt install -t bullseye-backports iproute2`
