### ISSUE TITLE
Improve doc with installation of `iproute` for `ss` command

### ISSUE THREAD

**Issue by lucasvc** [BlackReloaded/wsl2-ssh-pageant#19]
Adding the snippet for `.bashrc` in a Fedora basic image, `ss` command does not exist.
After an internet search (and confirmed using `yum provides`), it is provided by the `iproute` package, so would be good to confirm that new users has this command available on its computer.

**Note**: By the way, the command `ss` in my environment always output,
```
RTNETLINK answers: Invalid argument
```
so I added `2&> /dev/null ` to the command.

**Comment by tobiaskohlbau** [comment]
Hi,

regarding the output from `ss` see #17.

Regarding the missing tools of `ss` I've added a statement about the prerequisite of `wsl2-ssh-pageant` within the README itself.
