### ISSUE TITLE
Add support for GPG installed by scoop

### ISSUE THREAD

**Issue by mirror-kt** [BlackReloaded/wsl2-ssh-pageant#22]
[Scoop](https://scoop.sh) is a command line installation manager for Windows.

If I install GPG by scoop, the home directory of GPG will be placed in `%USERPROFILE%\scoop\apps\GnuPG\current\home` instead of `%APPDATA%\gnupg`.
However, in this project, the GPG home is hard-coded (FYI: [here](https://github.com/BlackReloaded/wsl2-ssh-pageant/blob/6a592d3245d03118f65ebb86d2990ffe9b705de0/main.go#L147)) and cannot support the GPG installed in scoop.

We would like to manage the version of GPG using scoop, can you support it?

**Comment by tobiaskohlbau** [comment]
Have a look into #2 where some aspects of this where already discussed. I proposed a solution by using a flag to point to the right path.

Would an flag like:

```
(setsid nohup socat UNIX-LISTEN:"$GPG_AGENT_SOCK,fork" EXEC:"$wsl2_ssh_pageant_bin --gpg S.gpg-agent --gpgwinpath XYZ" >/dev/null 2>&1 &)
```

help?

**Comment by tobiaskohlbau** [comment]
I just released [v1.3.0](https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/tag/v1.3.0) which includes an setting for this: `--gpgConfigBasepath`.

**Comment by mirror-kt** [comment]
Oh, I see, thank you!

**Comment by tobiaskohlbau** [comment]
Did it work?
