### ISSUE TITLE
No longer works in the preview version of WSL from Microsoft Store on Windows 11

### ISSUE THREAD

**Issue by DavidZidar** [BlackReloaded/wsl2-ssh-pageant#27]
**Describe the bug**
I tried the new preview version of WSL from the Microsoft Store that was just released, the only thing that no longer seems to be working is wsl2-ssh-pageant.

SSH no longer authorizes me with the key in my Yubikey but asks me for my password.

Uninstalling the preview version of WSL makes it work again.

**To Reproduce**
1. Setup wsl2-ssh-pageant
2. Install WSL from Microsoft Store on Windows 11
3. Try to use wsl2-ssh-pageant

**Expected behavior**
SSH connections should work like before.

**Additional context**
I reported the issue to [WSL](https://github.com/microsoft/WSL/issues/7521) as it is the only thing that has changed, but they suggested I report it here too.

Blog post: [A preview of WSL in the Microsoft Store is now available!](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/)

**Comment by tobiaskohlbau** [comment]
I've just installed the preview version. Looks like the new version does not allow to run _exe_ files from within the linux filesystem anymore. I would suggest for now moving the file anywhere into `/mnt/c` and update the startup scripts. Can you test this solution?

```
tobias@DESKTOP-FSD244A ~ [255]> ~/.ssh/wsl2-ssh-pageant.exe
/home/tobias/.ssh/wsl2-ssh-pageant.exe: Invalid argument
```

```
tobias@DESKTOP-FSD244A ~ [1]> /mnt/c/tmp/wsl2-ssh-pageant.exe
```

**Comment by DavidZidar** [comment]
@tobiaskohlbau You are right, moving the binary to `/mnt/c` made it work again.

**Comment by benhillis** [comment]
For most cases it shouldn't matter, but distros / users can opt-out of running the 9p server which would mean you could not run unless they were stored on a Windows volume.

**Comment by tobiaskohlbau** [comment]
Thanks @DavidZidar for verifying. I've tried to get the update but it wasn't available yesterday.
