### ISSUE TITLE
error fetching identities: communication with agent failed

### ISSUE THREAD

**Issue by dflorinidita** [BlackReloaded/wsl2-ssh-pageant#32]
output for `ssh-add -l`
error fetching identities: communication with agent failed 

have done a rm of sock
` rm .ssh/agent.sock `
sourced .bashrc_pagent
and sock was not created
outuput of `ssh-add -l`
Error connecting to agent: No such file or directory

>elif  ss -a | grep -q "$SSH_AUTH_SOCK" && [[ ! -f "$SSH_AUTH_SOCK" ]] ; then
	killall socat
	wsl2_ssh_pageant_bin="$HOME/.ssh/wsl2-ssh-pageant.exe"
	if test -x "$wsl2_ssh_pageant_bin"; then
	  (setsid nohup socat UNIX-LISTEN:"$SSH_AUTH_SOCK,fork" EXEC:"$wsl2_ssh_pageant_bin" >/dev/null 2>&1 &)
	else
	  echo >&2 "WARNING: $wsl2_ssh_pageant_bin is not executable."
	fi
	unset wsl2_ssh_pageant_bin
fi

actually this was created back

**Comment by tobiaskohlbau** [comment]
@dflorinidita are you willing to contribute your solution. In case someone else hits the same problem and searches the issue tracker.
