### ISSUE TITLE
Cannot open netlink socket: Protocol not supported

### ISSUE THREAD

**Issue by simonlaw0711** [BlackReloaded/wsl2-ssh-pageant#42]
**Describe the bug**
Error showing: Cannot open netlink socket: Protocol not supported

**To Reproduce**
1. Follow the steps and Install the pageant
2. Turn on WSL Ubuntu
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/92658511/176096521-698761e2-e0fd-482c-b860-c16c6e8538bb.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by tobiaskohlbau** [comment]
Please have a look into #28 looks like a duplicate.
