### ISSUE TITLE
Hide console output on launch

### ISSUE THREAD

**Issue by craftbyte** [BlackReloaded/wsl2-ssh-pageant#8]
When launching as per the README every first time starting up the WSL machine the following is displayed:
```
[2] 39
[2]  + 39 done       setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork  > /dev/null 2>&1
[2] 44
[2]  + 44 done       setsid nohup socat UNIX-LISTEN:$GPG_AGENT_SOCK,fork  > /dev/null 2>&1
```

Would it be possible to supress this output, I have tried with no luck.

**Comment by tobiaskohlbau** [comment]
Which shell are you using? Normally this should be suppressed already.

**Comment by craftbyte** [comment]
zsh with oh-my-zsh, found solution right after posting (parantheses):
```bash
export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
ss -a | grep -q $SSH_AUTH_SOCK
if [ $? -ne 0 ]; then
        rm -f $SSH_AUTH_SOCK
        (setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"$HOME/.ssh/wsl2-ssh-pageant.exe" >/dev/null 2>&1 &)
fi
export GPG_AGENT_SOCK=$HOME/.gnupg/S.gpg-agent
ss -a | grep -q $GPG_AGENT_SOCK
if [ $? -ne 0 ]; then
        rm -rf $GPG_AGENT_SOCK
        (setsid nohup socat UNIX-LISTEN:$GPG_AGENT_SOCK,fork EXEC:"$HOME/.ssh/wsl2-ssh-pageant.exe --gpg S.gpg-agent" >/dev/null 2>&1 &)
fi
```

**Comment by tobiaskohlbau** [comment]
Perfect otherwise this would be @BlackReloaded to answer as I’m not using zsh. Glad you found a solution! Now I’m curious if that’s something we should put into the README. @BlackReloaded do you have output on startup?

**Comment by craftbyte** [comment]
@tobiaskohlbau does it still work as intended on bash for you?

**Comment by tobiaskohlbau** [comment]
Yes I use exactly that shown settings on all of my machines.
